# Copyright the Hyperledger Fabric contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.rrr)
trigger: none
pr:
  - master
  - release-*

variables:
  - group: github

jobs:
  - job: DCO
    pool:
      vmImage: ubuntu-18.04
    steps:
      - checkout: none
      - script: |
          set -x

          pull_data=$(curl -u ${GIT_TOKEN}:${GIT_TOKEN} https://api.github.com/repos/${REPO_NAME}/pulls/${PR_NUMBER}/commits)
          BRANCH=$(echo ${pull_data} | jq -r .head.ref)
          AUTHOR=$(echo ${pull_data} | jq -r .head.user.login)

          commits=$(curl -u ${GIT_TOKEN}:${GIT_TOKEN} https://api.github.com/repos/${REPO_NAME}/pulls/${PR_NUMBER}/commits)
          IFS=$'\n' read -rd '' -a messages <<<"$(echo ${commits} | jq -c '.[].commit.message')" || true

          declare -a needs_dco
          index=0
          for message in "${messages[@]}"; do
             if [[ ! "${message}" =~ "Signed-off-by" ]]; then
                  commit_url=$(echo ${commits} | jq -r .[${index}].html_url)
                  needs_dco+=("${commit_url}")
             fi
             index=$((${index} + 1))
          done

          if [[ ${#needs_dco[@]} -ne 0 ]]; then
              echo "{\"body\":\"Hyperledger Fabric requires all commits to contain a DCO signoff. The following commits do not contain a proper signoff:\n\n$(printf '%s\\n' $(echo ${needs_dco[*]} | tr -s ' ' '\n'}))\n\nYou cannot add a DCO signoff using the GitHub UI. You must check out the branch locally and signoff your commits using the CLI.\n\nIf you haven't cloned your Fabric fork yet, issue the following command:\n\n\`git clone https://github.com/${AUTHOR}/fabric\`\n\`cd fabric\`\n\nYou can signoff your commits by issuing the following commands:\n\n\`git fetch origin\`\n\`git checkout ${BRANCH}\`\n\`git rebase --signoff HEAD~${#needs_dco[@]}\`\n\`git push origin ${BRANCH} -f\`\"}" > data.json

              comment_url="https://api.github.com/repos/${REPO_NAME}/issues/${PR_NUMBER}/comments"
              curl -u ${GIT_TOKEN}:${GIT_TOKEN} -X POST -d @data.json "${comment_url}"

              label_url="https://api.github.com/repos/${REPO_NAME}/issues/${PR_NUMBER}/labels"
              curl -u ${GIT_TOKEN}:${GIT_TOKEN} -X POST -d '{"labels": ["needs-dco-signoff"]}' "${label_url}"

              exit 1
          fi
        env:
          PR_NUMBER: $(System.PullRequest.PullRequestNumber)
          REPO_NAME: $(Build.Repository.Name)
          GIT_TOKEN: $(GITHUB_TOKEN)
        displayName: Validate Signature