# Copyright the Hyperledger Fabric contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

on:
  issue_comment:
    types: [created]
name: Automatically Trigger Azure Pipeline
jobs:
  trigger:
    name: TriggerAZP
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, 'test')
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Build
      run: |
        cat "${GITHUB_EVENT_PATH}"
      env:
        AZP_TOKEN: ${{ secrets.AZP_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
